### ISSUE TITLE
Special letters/ Codierung Sonderzeichen

### ISSUE THREAD

**Issue by OberfragGER** [Hirsch-DE/ioBroker.vds2465-server#1]
Hi,
der Adapter funktioniert hervorragend! Der Errichter der gerade da war, konnte anhand der Einstellungen problemlos nachvollziehen, was er zu tun hat. @neotrace hat dann noch telefonishc geholfen damit die Zustandsänderungen der Fenster im ioBroker sichtbar sind. Wow!

Kurz zum Bug:
Das "ö" als Sonderzeichen wird nicht richt richtig dargestellt. Eher ein Schönheitsfehler, zumindest auf meinem System.
![image](https://user-images.githubusercontent.com/28652993/213460847-5bd46aae-8ec2-4fdc-a2ea-1023d703825c.png)

Debian 10
Nodejs v16.18.1
NPM 8.19.2
js-controller 4.0.23

**Comment by Hirsch-DE** [comment]
Sollte mit Version 0.1.4 erledigt sein.
