### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [Hirsch-DE/ioBroker.vds2465-server#3]
## ioBroker adapter checker for npm access

Access right check for adapter vds2465-server returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.vds2465-server"

Current maintainers are 
    hirsch-de <npm37@hirschfeldonline.de>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by Hirsch-DE** [comment]
in npm 
Invitations 1
bluefox

**Comment by mcm1957** [comment]
access now OK
issue can be closed
THANKS
