### ISSUE TITLE
Update stable version in repo from 0.1.10 to 1.0.0

### ISSUE THREAD

**Issue by GermanBluefox** [Hirsch-DE/ioBroker.vds2465-server#8]
# Think about update stable version to 1.0.0
**Version**: stable=**0.1.10** (547 days old) => latest=**1.0.0** (29 days old)
**Installs**: stable=**85** (93.41%), latest=**5** (5.49%), total=**91**

Click to use [developer portal](https://www.iobroker.dev/adapter/vds2465-server/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2765)

**Do not close this issue manually as a new issue will be created if condition for update still exists.**

Please drop a comment if any reason exists which blocks updating to version 1.0.0 at this time.

Note: This is an automatically generated message and not personally authored by bluefox!
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
Please add node.js 22 tests
https://github.com/Hirsch-DE/ioBroker.vds2465-server/issues/7

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 1.0.0 but the current stable version is already 1.0.0.

So this issue should be closed.

@mcm1957 for evidence
